### ISSUE TITLE
Some questions regarding KMISPool 

### ISSUE THREAD

**Issue by flandolfi** [goose315/Graph_Pooling_Benchmark#1]
Hi,

First of all, thank you and your team for the amazing work of benchmarking many pooling methods, including KMISPool.

I'm Francesco, an author of the KMIS-pooling method that you included in your paper. I was wandering, why did you set `k=5` on all experiments? I believe this will make KMISPool underperform on all datasets, since it basically assumes that every graph has diameter > 5, which is a strong assumption for the datasets you took in considerations (that have only small-sized graphs). This setting will probably produce a single cluster for every graph, making it a de-facto global pooling instead of a hierarchical one. In my AAAI experiments the grid-search always returned `k=1` among a space of {1, 2, 3}. Setting `k=5` is like using a pooling on images with pooling size 6x6... it's a huge value.

Another question: KMISPooling does not allow the selection of a pooling ratio such as TopK. So, how did you manage to fix it in the experiments in the appendix (Tables 10,11,12,13)?

Thank you so much!

Bests,
Francesco

**Comment by goose315** [comment]
Thank you very much for your attention to this project and for your valuable comments! We also sincerely thank you and your team for developing KMISPooling. It is a powerful and valuable method, and we deeply appreciate your contribution to the knowledge.

Regarding the first issue you raised, we will reset the  k  value of the kmispooling to 1 in the next version and update the relevant content in the paper accordingly. We will also make a more explicit recommendation in our GitHub repository for people to use smaller  k  values when applying kmispool to small-scale graph data.

For the second issue, we will check the results for the appendix tables, and revise them in the upcoming version.

Finally, we sincerely appreciate your valuable suggestions for this project. We will focus on updating and revising the above-mentioned issues in the upcoming version.

Best regards,
Pengyun
